### ISSUE TITLE
Auto-Registering Middleware?

### ISSUE THREAD

**Issue by m1guelpf** [spatie/laravel-demo-mode#13]
Is there an specific reason why you tell your users to register the middleware when you can use aliasMiddleware() in the service provider?

**Comment by freekmurze** [comment]
Not sure, but I believe this has been done because `aliasMiddleware` is not named the same in the different versions of Laravel this package supports.

When creating a new major version of the package that targets L5.5, we'll probably register the middleware in the service provider again.
