### ISSUE TITLE
Redundant method

### ISSUE THREAD

**Issue by amitmerchant1990** [spatie/laravel-demo-mode#29]
Hi guys,

I'm a little bit confused here. What's the purpose of this method `protectedByDemoMode()` here if it's always going to return `true` irrespective of what has been passed to it as a parameter?

https://github.com/spatie/laravel-demo-mode/blob/10d7cff1a77c22ab27511c98c33f73a279786d44/src/DemoMode.php#L45

Regards.

**Comment by rcubitto** [comment]
I think this method can be removed. It used to return `$this->config['enabled']` but that's handled right above it.

**Comment by amitmerchant1990** [comment]
@freekmurze Can I go ahead to fix this?

**Comment by freekmurze** [comment]
If you extend `DemoMode` you only need to `protectedByDemoMode` to customize the behaviour a bit. 

Removing this method now is a breaking change for people who are using this now.
