### ISSUE TITLE
Demo url Accessable by logged in user

### ISSUE THREAD

**Issue by akhzarjaved** [spatie/laravel-demo-mode#31]
Hi,
This might not be an issue but i'm a bit confused.
When a user is logged in he can access the URL which has demoMode middleware.
Isn't the middleware was suppose to restrict the URL to be accessible by anyone (Except the IP's given in config array)

![image](https://user-images.githubusercontent.com/50201631/100070117-5cdfbb00-2e5b-11eb-8ee2-f677aa3657f5.png)

**Comment by m-bosch** [comment]
I think it is a pretty good assumption that when you are logged in to the application you will be allowed too.  Before you are logged in you should be within the authorized-ip scope.
