### ISSUE TITLE
Support for Laravel 9

### ISSUE THREAD

**Issue by RobinBastiaan** [spatie/laravel-demo-mode#35]
When trying out Laravel 9 on a fresh install, I get the following error message. Given the usefulness and continued value of this page, I hope it is possible to resolve this problem.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/laravel-demo-mode 2.7.1 requires illuminate/support ^7.0|^8.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires spatie/laravel-demo-mode ^2.7 -> satisfiable by spatie/laravel-demo-mode[2.7.0, 2.7.1].
```

**Comment by freekmurze** [comment]
Hi, we won't update this package, as the functionalities are now included in Laravel's native `down` command.

**Comment by RobinBastiaan** [comment]
I am sad to hear that, because I do not agree the down command is a suitable replacement for this package. Most notably is that one needs to manually enable the down command (and do not forget to disable it again), while the demo-mode from this package can be run continuously and shared asynchronously with other people.

Anticipating the reasons listed above did not change your perspective, I would like to try to update this myself. Am I welcome to put in a PR, or would you prefer me to make a fork? Anyways, thank you very much for this wonderful package!

**Comment by freekmurze** [comment]
If you send a PR to make it compatible with L9 and all the tests pass, then I'll merge it in 👍
